Blueprints/auth.py
from flask import Blueprint,request,redirect,url_for
from Models import User
auth = Blueprint('auth',__name__)


@auth.route('/login',methods=["POST"])
def login():
    formdata = request.form
    username,password = [formdata.get('username'),formdata.get('password').encode('utf-8')]
    if(User.loginuser(username,password)==200):
        return redirect(url_for('views.homepage'))
    else:
        return redirect(url_for('views.index'))


@auth.route('/signup',methods=["POST"])
def signup():
    formdata = request.form
    username,password, name = [formdata.get('username'),formdata.get('password').encode('utf-8'),formdata.get('name')]
    if (User.signupuser(username, password,name) == 200):
        return redirect(url_for('views.homepage'))
    else:
        return redirect(url_for('views.index'))

Blueprints/views.py
import json
from flask import Blueprint,render_template,Response,session
from flask_login import current_user,login_required
from Models import Hobby

views = Blueprint('views',__name__)

app_specific_path = 'UserFunctionTemplates_APPSPECIFIC'
@views.route('/')
def index():
    return render_template('index.html')

@views.route('/auth/<what>')
def authview(what):
    if(what=='login'):
        return render_template('loginform.html')
    elif(what=='signup'):
        return render_template('signupform.html')



@views.route('/homepage')
@login_required
def homepage():
    if(current_user.is_authenticated):
        response = Response(render_template('homepage.html',props=current_user.props))
        response.headers['Cache-control'] = 'no-cache'
        return response






@views.route('/homepage/viewuserhobby')
@login_required
def viewuserhobby():
    hobbies = current_user.getHobbies()

    return render_template(f'{app_specific_path}/viewuserhobby.html',hobbies=hobbies)



@views.route('/homepage/viewuserfriends')
@login_required
def viewuserfriends():
    return render_template(f'{app_specific_path}/viewuserfriends.html', user=current_user)


@views.route('/homepage/viewuserprogress')
@login_required
def viewuserprogress():
    return render_template(f'{app_specific_path}/viewuserprogress.html', user=current_user)



@views.route('/homepage/searchnewhobbies')
@login_required
def searchnewhobbies():
    return render_template(f'{app_specific_path}/searchnewhobbies.html', user=current_user)


@views.route('/homepage/viewuserhobby/addhobbyform')
@login_required
def HobbyForm():
    hobbies = Hobby.getall()
    return render_template(f'{app_specific_path}/addhobbyform.html',hobbies=hobbies)


@views.route('/homepage/viewuserprogress/setProgressCheck')
def setProgressCheck():
    hobbies = current_user.getHobbies()
    hobbies = list(filter(lambda a:a['ISPROGRESSCHECKACTIVE']==0, hobbies))
    lenofhobbies = len(hobbies)
    response = Response(render_template(f'{app_specific_path}/SettingNewProgressCheck.html',hobbies=hobbies,len=lenofhobbies))
    return response


@views.route('/homepage/viewuserprogress/seeProgressCheck')
def seeProgressCheck():
    hobbies = current_user.getHobbies()

    with_progress_check = list(filter(lambda a:a['ISPROGRESSCHECKACTIVE']==1,hobbies))
    print(with_progress_check)
    response = Response(render_template(f'{app_specific_path}/ViewAvailableProgress.html',hobbies=with_progress_check,length=len(with_progress_check)))
    return response


@views.route('/error')
def errorpage():
    return -100



@views.route('/homepage/viewuserfriends/viewfriends')
@login_required
def viewfriends():
    all_friends = current_user.get_friends()
    response = Response(render_template(f'{app_specific_path}/listoffriends.html',friends=all_friends,friendlen=len(all_friends)))

    return response

@views.route('/homepage/viewuserfriends/viewfriendsuggestions')
@login_required
def viewfriendsuggestions():
    response = Response(render_template(f'{app_specific_path}/findfriends.html'))

    return response

main.py
import secrets
from flask import Flask
from Blueprints.views import  views
from Blueprints.auth import auth
from Blueprints.Methods import methods
from flask_login import LoginManager
from Models import User



app = Flask(__name__)


app.secret_key = secrets.token_hex(32)
lm = LoginManager()

lm.init_app(app)

lm.login_view = 'views.index'


app.register_blueprint(views)
app.register_blueprint(auth)
app.register_blueprint(methods)


@lm.user_loader
def loaduser(userid):
    return User.loaduserusingusername(userid)

if(__name__=='__main__'):
    app.run(debug=True)

templates/UserFunctionTemplates_APPSPECIFIC/SettingNewProgressCheck.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col justify-center items-center bg-black  h-[100vh] w-[100vw]  gap-[10px] " id="FULLCONTENT">
    <form method="POST" action="{{url_for('methods.setCheckonHobby')}}" class="flex flex-col p-[80px] items-center gap-[10px] rounded-lg bg-white w-fit" >
        {% if len==0 %}
                       <h3 class="text-[#3F784C] text-5xl font-mono font-bold">NO HOBBIES FOUND</h3>
        {% else %}
            <label class="font-mono font-bold text-black">Hobby Name:</label>
            <select  name="hobbyname"  class="rounded-lg bg-black text-white font-bold font-mono p-[10px]">

                <option selected disabled hidden></option>
                {% for i in hobbies %}
                    <option >{{i['hobbyname']}}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Start" class="flex flex-col items-center justify-center p-[10px] font-bold bg-green-500 text-white rounded-lg w-fit hover:shadow-md hover:shadow-black"/>
        {% endif %}
    </form>

</div>

{% endblock %}

templates/UserFunctionTemplates_APPSPECIFIC/ViewAvailableProgress.html
{% extends 'base.html' %}

{% block content %}

{% if length==0 %}
<div class="flex flex-col justify-center items-center bg-black  h-[100vh] w-[100vw]  gap-[10px] " id="FULLCONTENT">
    <div class="flex flex-col items-center gap-[10px]">
        <h1 class="text-red-500 font-bold text-5xl font-mono">No Hobbies have Progress Check Enabled</h1>
        <p class="font-bold text-lg font-mono text-white">Click <a href="{{url_for('views.setProgressCheck')}}" class="animate-pulse text-red-500" >here</a> to set a new progress check on a hobby</p>
    </div>
</div>
{% else %}
<div class="flex flex-col justify-start bg-black  h-[100vh] w-[100vw]  gap-[10px] " id="FULLCONTENT">

        {% for i in hobbies %}
            {% if i['PROGRESS']>=0.0 and i['HOBBYCOMPLETED']!='COMPLETED' %}
                    <div class="bg-red-500 rounded-lg p-[40px] flex flex-col items-center w-fit mt-[5px]">
                        <h1 class="text-white font-bold text-5xl font-mono">{{i['hobbyname']}}</h1>
                        <button id="{{i['hobbyname']}}" class=" UpdateProgressBtn font-bold text-lg font-mono text-white">{{i['PROGRESS']}}</button>
                    </div>
            {% elif i['HOBBYCOMPLETED']=='COMPLETED' %}
                <div class="bg-green-500 rounded-lg p-[40px] flex flex-col items-center w-fit mt-[5px]">
                    <h1 class="text-white font-bold text-5xl font-mono">{{i['hobbyname']}}</h1>
                    <button id="{{i['hobbyname']}}" class=" UpdateProgressBtn font-bold text-lg font-mono text-white">{{i['progress']}}</button>
                </div>

            {% endif %}

        {% endfor %}
</div>
{% endif %}


<script>
    let updateProgressButtons = document.getElementsByClassName('UpdateProgressBtn');
    let contentdiv = document.getElementById('FULLCONTENT');


    for(const i of updateProgressButtons){
            i.addEventListener('click', async (event)=>{
                 let targethobby = event.target.id;
                let milestones_completed= []
                const updateMilestones = async ()=>{
                    milestones_completed = milestones_completed.map((item)=>{
                        return item.replace('MILESTONE','');
                    });
                    let bodyObj = {}
                    bodyObj.milestones = milestones_completed;
                    bodyObj.targethobby = targethobby
                    let res = await fetch('{{url_for('methods.updatemilestoneprogress')}}',{
                        method:'POST',
                        headers:{
                            'Content-Type':'application/json'
                        },
                        body:JSON.stringify(bodyObj)
                    })

                    let data = await res.json();

                    if(data.statuscode==200){
                        alert('Updated Progress Successfully');
                    }
                    else{
                        alert('Some Problem');
                    }
                    location.reload();
                }
                let div = document.createElement('div');

                div.classList.add('flex','flex-col','items-center','gap-[10px]','bg-white','p-[50px]','rounded-lg','w-[80vw]','h-[50vh]');

                let title = document.createElement('h1');
                title.classList.add('font-lg','font-mono','text-black');
                title.innerText= `Update Progress for ${targethobby}`;


                let obj = {}
                obj.hobbyname = targethobby
                let res = await fetch(`{{url_for('methods.getmilestones')}}`,{
                    method:'POST',
                    headers:{
                        'Content-Type':'application/json'
                    },
                    body: JSON.stringify(obj)
                });

                let data = await res.json()

                if(data.milestones=='NotFound'){
                        let nonefound = document.createElement('h1');
                        nonefound.classList.add('font-mono','font-bold','text-green-500', 'text-lg');
                        nonefound.innerText = 'Hooray No Milestone Lefttttttt';
                        div.appendChild(nonefound);

                }
                else{


                let milestones = Array.from(data.milestones);

                let divofrows = document.createElement('div');
                divofrows.classList.add('flex','flex-row','gap-[10px]','w-fit');

                for(const i of milestones){
                        console.log(i);
                        let index = milestones.indexOf(i);
                        let temp = document.createElement('div');
                        temp.id =   `MILESTONE${index+1}`;
                        temp.classList.add('rounded-lg',`bg-stone-${400+index*100}`,'p-[10px]','hover:cursor-pointer');
                        temp.innerText = i;
                        divofrows.appendChild(temp);
                        temp.addEventListener('click',()=>{
                            if(milestones_completed.length>=1){
                                alert('You can push a max of 1 milestone at a time');
                                return;
                            }
                            else{
                                    temp.classList.add('opacity-[0.5]');
                                    milestones_completed.push(temp.id);
                            }

                        });
                }

                div.appendChild(title);
                div.appendChild(divofrows);

                let complete_progress_update_button= document.createElement('button');
                complete_progress_update_button.classList.add('btnclass');
                complete_progress_update_button.innerText = `Update Progress`;
                complete_progress_update_button.addEventListener('click',()=>{
                    updateMilestones();
                })
                div.appendChild(complete_progress_update_button);
            }
                contentdiv.innerHTML = '';
                contentdiv.appendChild(div);

            })
    }
</script>

{% endblock %}

templates/UserFunctionTemplates_APPSPECIFIC/addhobbyform.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" action="{{url_for('methods.addHobby')}}" class="flex flex-col p-[40px] items-center gap-[10px] rounded-lg bg-white w-fit">
    <div class="flex flex-row gap-[10px] items-center">
        <label class="text-white font-mono font-bold w-fit">Hobby Name:</label>

        <select id="typeoptions" name="hobbyname" class="rounded-lg bg-black text-white font-bold font-mono p-[10px]">
            <option selected disabled hidden></option>
            {% for i in hobbies %}
                <option>{{i}}</option>
            {% endfor %}

        </select>

    </div>
    <div class="flex flex-col gap-[10px] items-center">
        <label class="text-black font-mono font-bold w-fit">Set 5 Progress Levels aka MileStones</label>
        <div class="flex flex-row gap-[5px] w-fit justify-around">
                <input type="text" class="p-[10px] rounded-lg bg-stone-400 font-bold text-white font-mono" name="Progress1">
                 <input type='text' class="p-[10px] rounded-lg bg-stone-500 font-bold text-white font-mono" name="Progress2">
                 <input type='text' class="p-[10px] rounded-lg bg-stone-600 font-bold text-white font-mono" name="Progress3">
                 <input type='text' class="p-[10px] rounded-lg bg-stone-700 font-bold text-white font-mono" name="Progress4">
                 <input type='text' class="p-[10px] rounded-lg bg-stone-800 font-bold text-white font-mono" name="Progress5">
        </div>
    </div>

    <input type="submit" class="flex flex-col items-center justify-center p-[10px] font-bold bg-green-500 text-white rounded-lg w-fit" value="add"/>
</form>


{% endblock %}

templates/UserFunctionTemplates_APPSPECIFIC/findfriends.html
{% extends 'base.html' %}

{% block content %}


<div class="flex flex-row gap-[0px] w-[100vw] h-[100vh] bg-black" id="fullcontent">
        <div class="h-[100vh] w-[33vw] border-r-[5px] border-black flex flex-col justify-center items-center bg-sky-900 font-bold font-mono text-white hover:opacity-[0.5] hover:cursor-pointer" id="byhobby">
            <h1>Find</h1>
            <h1>Friends</h1>
            <h1>By</h1>
            <h1>Hobbies</h1>
        </div>
          <div class="h-[100vh] w-[33vw] border-r-[5px] border-black flex flex-col justify-center items-center bg-red-900 font-bold font-mono text-white  hover:opacity-[0.5] hover:cursor-pointer" id="byname">
            <h1>Find</h1>
            <h1>Friends</h1>
            <h1>By</h1>
            <h1>USERNAME</h1>
        </div>
        <a class="h-[100vh] w-[33vw] border-r-[5px] border-black flex flex-col justify-center items-center bg-green-900 font-bold font-mono text-white  hover:opacity-[0.5] hover:cursor-pointer" id="byrandom" href="{{url_for('methods.searchrandompeople')}}">
            <h1>Find</h1>
            <h1>Friends</h1>
            <h1>By</h1>
            <h1>Random</h1>
        </a>
</div>


<script>
    let byname = document.getElementById('byname');
    let byhobby = document.getElementById('byhobby');
    let byrandom = document.getElementById('byrandom');

    let fullcontent = document.getElementById('fullcontent');
    byname.addEventListener('click',function handleClick(){
            byname.removeEventListener('click',handleClick);
            let div = document.createElement('form');
            div.classList.add('flex','flex-col','items-center','gap-[10px]');
            div.setAttribute('method','POST')
            div.setAttribute('action','{{url_for('methods.searchfriendbyname')}}')
            let label = document.createElement('label');
            label.innerText = 'Name of the Friend'
            label.classList.add('font-mono','font-bold','text-white');
            let inpelem = document.createElement('input');
            inpelem.classList.add('font-mono','font-bold','text-black','bg-white','p-[20px]','rounded-lg','w-[100%]');
            inpelem.name = 'name'
            let subbutton = document.createElement('button');
            subbutton.classList.add('btnclass');

            subbutton.innerText = 'search'

            div.appendChild(label);
            div.appendChild(inpelem);
            div.appendChild(subbutton);

            byname.innerHTML = ''
            byname.appendChild(div);


    })

    byhobby.addEventListener('click',function handleClick(){
        byhobby.removeEventListener('click',handleClick);
        let div = document.createElement('form');
            div.classList.add('flex','flex-col','items-center','gap-[10px]');
            div.setAttribute('method','POST')
            div.setAttribute('action','{{url_for('methods.searchfriendsbyhobby')}}');
            let label = document.createElement('label');
            label.innerText = 'Hobby of the Friend'
            label.classList.add('font-mono','font-bold','text-white');

            let inpelem = document.createElement('input');
            inpelem.type='text';
            inpelem.classList.add('font-mono','font-bold','text-black','bg-white','p-[20px]','rounded-lg','w-[100%]');
            inpelem.name = 'hobby'
            let subbutton = document.createElement('button');
            subbutton.classList.add('btnclass');
            subbutton.innerText = 'search'

            div.appendChild(label);
            div.appendChild(inpelem);
            div.appendChild(subbutton);

            byhobby.innerHTML = ''
            byhobby.appendChild(div);
    })


</script>
{%endblock%}

templates/UserFunctionTemplates_APPSPECIFIC/listoffriends.html
{% extends 'base.html' %}

{% block content %}

<div class="bg-black w-[100vw] h-[100vh] flex flex-col justify-center items-center overflow-auto">
        {% if friendlen == 0 %}
            <div class="flex flex-col items-center">
                 <h1 class="font-mono text-3xl text-green-500 font-bold">No Friends found</h1>
                <span class="font-mono text-sm text-red-500 font-bold">But dont worry <a class="text-sky-500 " href="{{url_for('views.viewfriendsuggestions')}}">make new friends here</a></span>
            </div>
        {% else %}
            <div class="bg-white w-[40vw] h-[60vh] rounded-lg flex flex-col items-center gap-[40px]">
                        <h3 class="font-mono font-bold text-red-500 text-lg" id="Name">{{friends[0]['name']}}</h3>
                        <div class="flex flex-row gap-[10px] items-center">
                            <button onClick=goprev class="rounded-lg p-[10px] bg-red-500 text-white"><-</button>
                            <button onClick=gonext class="rounded-lg p-[10px] bg-green-500 text-white">-></button>
                        </div>
            </div>
        {% endif %}
</div>
<script>
    let index = 0;
    let friends = Array.from({{friends | tojson }})
    let name = document.getElementById('Name');
    const goprev = ()=>{
            index--;
            if(index<0){
                return
             }
             else{
                name.innerText = friends[index]['name'];
            }

    }

    const gonext = ()=>{
        index++;
        if(index>=friendlen){
            return;
        }
        else{
                name.innerText = friends[index]['name'];
        }
    }




</script>


{% endblock %}

templates/UserFunctionTemplates_APPSPECIFIC/viewuserfriends.html
{% extends 'base.html' %}

{% block content %}

<div class="flex flex-col justify-center items-center h-[100vh] w-[100vw] bg-black gap-[10px]" id="FULLCONTENT">
    <div class="flex flex-row gap-[30px]">
            <a href='{{url_for("views.viewfriends")}}' class="rounded-lg bg-red-500 p-[30px] flex flex-col items-center justify-center text-white font-bold font-mono hover:opacity-[0.50] hover:cursor-pointer">View Friends</a>
            <a href='{{url_for("views.viewfriendsuggestions")}}' class="rounded-lg bg-red-500 p-[30px] flex flex-col items-center justify-center text-white font-bold font-mono hover:opacity-[0.50] hover:cursor-pointer">Add New Friend</a>
    </div>
</div>

{% endblock %}

templates/UserFunctionTemplates_APPSPECIFIC/viewuserhobby.html
{% extends 'base.html' %}

{% block  content %}
<div class="flex flex-col justify-center items-center  h-[100vh] w-[100vw] bg-black gap-[10px] "  id="FULLCONTENT">

    <div class="rounded-lg w-[700px] h-[700px] flex flex-col items-center justify-center  border-white   font-bold bg-black  text-black font-mono" id="hobbyspace">
        hello
    </div>
    <div class="flex flex-row justify-end w-[45vw]">
      <button class="rounded-lg p-[10px] flex flex-col items-center justify-center font-bold font-mono text-black bg-white " onclick=getHobbyForm()>Add new hobby</button>
        </div>
</div>

<script>
    let hobbies ={{hobbies|tojson}};
    console.log(hobbies);
    let hobbyspacediv= document.getElementById('hobbyspace')
    let contentdiv = document.getElementById('FULLCONTENT');



    const getHobbyForm = async ()=>{
        console.log('click');
        let res = await fetch('{{url_for('views.HobbyForm')}}',{
            method:'GET',

        });

        let data = await res.text()
        contentdiv.innerHTML= data;

    }
    console.log(hobbies);
    if(hobbies.length>0){
        var index = 0
        setInterval(()=>{
            console.log('interval');
            if(index==hobbies.length){
                index = 0
            }else{

            hobbyspacediv.innerHTML = `<h1 class="font-mono text-5xl text-white font-bold tracking-widest">${hobbies[index].hobbyname}</h1>
                        <h2 class='font-mono text-lg text-red-500 font-bold'>${hobbies[index].hobbytype}</h1>
            `
            index++;
            }
        },5000)
        console.log(hobbies);
    }
    else{
        console.log('hey');
         hobbyspacediv.innerHTML = '<h3 class="text-[#3F784C] text-5xl font-mono font-bold">NO HOBBIES FOUND</h3>'
    }



</script>

{% endblock %}

templates/UserFunctionTemplates_APPSPECIFIC/viewuserprogress.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col justify-center items-center  h-[100vh] w-[100vw] bg-black gap-[10px]" id="FULLCONTENT">
    <div class="flex flex-row gap-[10px] ">
        <a class="rounded-lg p-[40px] bg-purple-500 text-black font-mono font-bold animate-colorchangeWhitetoPurple" href="{{url_for('views.setProgressCheck')}}">Set a New Progress Check</a>
        <a class="rounded-lg p-[40px] bg-white text-black font-mono font-bold animate-colorchangePurpletoWhite" href="{{url_for('views.seeProgressCheck')}}">See Progress Check</a>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HobbyBook</title>
    <link rel="stylesheet" href="{{url_for('static',filename='output.css')}}" >
</head>
<body>
  {% block content %}

  {% endblock %}
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% block content %}
<div class="flex flex-col w-[100vw] h-[100vh] justify-center items-center  bg-black" id="fullcontent">
    <h1 class="text-red-500 p-[80px] font-bold font-mono text-5xl w-[100%] h-[20%] "> Welcome <span id='profile' class="animate-pulse"> {{props['name'] }} </span></h1>
    <div class="flex flex-row justify-center  w-[100%] h-[80%]  ">

    <div class="flex flex-col gap-[10px] justify-center items-center w-[30%] h-[100%]">
        <a class="flex flex-col items-center rounded-lg p-[40px] w-[40%] h-[30%] bg-white" href="{{url_for('views.viewuserhobby')}}">
            <h1  class="font-bold text-black">Your Hobbies</h1>
            <img src="{{url_for('static',filename='assets/Hobbies.png')}}" alt="hobbies" class="homepageimg"/>
        </a>
        <a class=" flex flex-col items-center rounded-lg p-[40px] w-[40%] h-[30%] bg-white"  href="{{url_for('views.viewuserfriends')}}">
            <h1 class="font-bold text-black">View Friends</h1>
            <img src="{{url_for('static',filename='assets/Friends.png')}}" alt="hobbies" class="homepageimg" />
        </a>

    </div>
    <div class="flex flex-col gap-[10px] justify-center items-center w-[30%] h-[100%]" >

        <a class=" flex flex-col items-center rounded-lg p-[40px] w-[40%] h-[30%] bg-white"  href="{{url_for('views.viewuserprogress')}}">
            <h1 class="font-bold text-black">Track Progress</h1>
            <img src="{{url_for('static',filename='assets/Progress.png')}}" alt="hobbies"  class="homepageimg"/>
        </a>
        <a class=" flex flex-col items-center rounded-lg p-[40px] w-[40%] h-[30%] bg-white"  href="{{url_for('views.searchnewhobbies')}}">
              <h1 class="font-bold text-black">Search new Hobbies</h1>
            <img src="{{url_for('static',filename='assets/SearchThings.png')}}" alt="hobbies"  class="homepageimg"/>
        </a>


    </div>
</div>


</div>

<script>
    let profile = document.getElementById('profile');
    profile.addEventListener('click',()=>{
        let user_props = {{props|tojson}};
        let div = document.createElement('div');
        let fullcontent = document.getElementById('fullcontent');
        div.classList.add('flex','flex-col','gap-[10px]','bg-white','font-bold','font-mono','text-black','items-center','w-fit','p-[20px]','rounded-lg');
        for (let i in user_props){
            let temp = document.createElement('p');
            temp.innerText = `${i}:${user_props[i]}`
            div.appendChild(temp);
        }
        let goback = document.createElement('button');
        goback.classList.add('btnclass');
        goback.innerText = 'close'
        let children = fullcontent.children;

        goback.addEventListener('click',()=>{
            for(const i of children){
               if(i!=div){
                 i.style.removeProperty('filter');

               }
            }

            fullcontent.removeChild(div);
        })
        div.appendChild(goback);

         for(const i of children){
               if(i!=div){
                 i.style.filter = 'blur(8px)';
            }
          }
        fullcontent.appendChild(div);


    })
</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="flex flex-col items-center justify-center h-[100vh] w-[100vw] bg-black">
    <div class="flex flex-row gap-[10px]" id="content">
        <div class="w-32 h-32  rounded-full bg-red-700 hover:animate-pulse font-bold text-white flex flex-col items-center justify-center">
            <button id="loginbut" class="text-3xl font-mono ">Login</button>
        </div>
        <div class="w-32 h-32 p-[5px] rounded-full bg-green-700 hover:animate-pulse font-bold text-white flex flex-col items-center justify-center">
            <button id="signupbut" class="text-3xl font-mono">Sign-Up</button>
        </div>
    </div>
</div>
<script>
    let loginbut = document.getElementById('loginbut');
    let signupbut = document.getElementById('signupbut');

    let contentdiv = document.getElementById('content');
    loginbut.addEventListener('click',async ()=>{
       let res = await fetch('{{url_for('views.authview',what='login')}}',{
            method:'GET'
        })

        let data = await res.text()
        contentdiv.innerHTML = data;

    })
    signupbut.addEventListener('click',async ()=>{
       let res = await fetch('{{url_for('views.authview',what='signup')}}',{
            method:'GET'
        })

        let data = await res.text()
        contentdiv.innerHTML = data;

    })
</script>
{% endblock %}

templates/loginform.html
<form class="flex flex-col items-center rounded-lg bg-red-700 gap-[10px] p-[20px]" method="POST" action="{{url_for('auth.login')}}">
  <div class="flex flex-row gap-[10px] items-center">
        <label for="username" class="text-white font-mono font-bold">Username:</label>
        <input type="text" class="bg-white p-[10px] rounded-lg text-black font-mono font-bold" name="username">
  </div>
    <div class="flex flex-row gap-[10px] items-center">
        <label for="password" class="text-white font-mono font-bold">Password:</label>
        <input type="password" class="bg-white p-[10px] rounded-lg text-black font-mono font-bold" name="password">
  </div>
  <input type="submit" value="Hop in" class="p-[10px] rounded-lg bg-white text-black font-mono font-bold hover:opacity-[0.5]">
</form>

templates/signupform.html
<form class="flex flex-col items-center rounded-lg bg-green-700 gap-[10px] p-[20px]" method="POST" action="{{url_for('auth.signup')}}">
  <div class="flex flex-row gap-[10px]  items-center">
        <label for="username" class="text-white font-mono font-bold">Username:</label>
        <input type="text" class="bg-white p-[10px] rounded-lg text-black font-mono font-bold" name="username">
  </div>
    <div class="flex flex-row gap-[10px]  items-center">
        <label for="password" class="text-white font-mono font-bold">Password:</label>
        <input type="password" class="bg-white p-[10px] rounded-lg text-black font-mono font-bold" name="password">
  </div>
        <div class="flex flex-row gap-[40px]  items-center">
        <label for="Name" class="text-white font-mono font-bold">Name:</label>
        <input type="text" class="bg-white p-[10px] rounded-lg text-black font-mono font-bold" name="name">
  </div>
  <input type="submit" value="Hop in" class="p-[10px] rounded-lg bg-white text-black font-mono font-bold hover:opacity-[0.5]">
</form>